version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "8080:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:securepassword@db:5432/taskapp
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PORT=5000
      - STATIC_FOLDER=/static
      - TEST_ENV_VAR=Environment variable works!
    depends_on:
      - db
    volumes:
      - static_volume:/static
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_DB=taskapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d taskapp"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
  static_volume:
