version: "3.8"

x-db-env: &db_env
  MYSQL_DATABASE: ${MYSQL_DATABASE}
  MYSQL_USER:     ${MYSQL_USER}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  MYSQL_PORT: ${MYSQL_PORT}

services:

  db:
    image: mysql:8.0
    container_name: lab05-db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1",
              "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      start_period: 10s
      retries: 5
    volumes:
      - db-data:/var/lib/mysql

  api:
    platform: linux/amd64
    build:
      context: ./spring-backend
    container_name: lab05-api
    environment:
      <<: *db_env
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: ./react-frontend
    container_name: lab05-web

  reverse-proxy:
    build:
      context: ./nginx
    container_name: lab05-proxy
    volumes:
      - proxy-html:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      api:
        condition: service_started
      web:
        condition: service_started

volumes:
  db-data:
  proxy-html:
